# Generated by Django 4.1 on 2022-09-17 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Problem ID'),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('profile', 'problem_id')},
        ),
    ]
