# Generated by Django 4.1 on 2022-09-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_problem_is_active_alter_problem_problem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='is_active',
        ),
    ]
